### ISSUE TITLE
Unidentified image error when training model

### ISSUE THREAD

**Issue by colbyrand** [weecology/DeepForest#728] opened 2024-07-24 18:28 UTC
I am getting the following unidentified image error when I run "m.trainer.fit(m)": PIL.UnidentifiedImageError: cannot identify image file '/content/drive/MyDrive/ACFL_Colab/Data/Imagery/ACFL_Whistle_Lake_Training_Area_Pictometry_2023_3in.tif'.

This is the correct link to the image file I used to successfully predict tree crowns with no training data, so I am not sure why this image is not working when trying to train the model using hand annotated tree crowns.

Any suggestions on how to fix this error would be greatly appreciated!

**Comment by bw4sz** [comment] 2024-07-24 19:19
That's an interesting error. Can you paste the entire code please and drop the file in here? let's have a look at the file in PIL, Rasterio on its own and then in deepforest. That error would suggest this is way upstream of any of our code, but its a strange one if what you say is correct.

**Comment by colbyrand** [comment] 2024-07-24 20:20
Here is the code I am using:

`# Install packages
! pip install --upgrade deepforest
! pip install git+https://github.com/weecology/DeepForest.git

#load the modules
import os
import time
import numpy as np
import pandas as pd
from deepforest import main
from deepforest import get_data
from deepforest import utilities
from deepforest import preprocess
import geopandas as gpd
import matplotlib.pyplot as plt

#load model
model = main.deepforest()
model.use_release()

#Accessing data from drive
from google.colab import drive
drive.mount('/content/drive')

#Accessing the datasets
trainshp = '/content/drive/MyDrive/ACFL_Colab/Data/Crown_delin/Training/ACFL_Whistle_Lake_Training.shp'
train_img = '/content/drive/MyDrive/ACFL_Colab/Data/Imagery/ACFL_Whistle_Lake_Training_Area_Pictometry_2023_3in.tif'

#reading the raster
import rasterio as ras
train_img_file = ras.open(train_img)
transform = train_img_file.transform
crs = train_img_file.crs
crs

# Predict the image (no training data)
boxes = model.predict_tile(train_img, return_plot = False, patch_size=700,
                           patch_overlap=0.25, iou_threshold= .4)
boxes.head()

gdf = utilities.annotations_to_shapefile(boxes, transform=transform, crs=crs)
gdf.to_file("/content/drive/MyDrive/ACFL_Colab/Data/Crown_delin/ACFL_Whistle_Lake_Training_Area_Crowns")

# Predict the image (with training data)
#Visualizing the shapefile
trainshp_file =gpd.read_file(trainshp)
trainshp_file.plot()

# Converting the training shapefile to annotations
df_train = utilities.shapefile_to_annotations(shapefile= (trainshp),
                                        rgb= (train_img) )
df_train.head()

#load the image file corresponding to the annotaion file
training_set_path = os.path.dirname(train_img)

#Write converted dataframe to file. Saved alongside the images
df_train.to_csv(os.path.join(training_set_path, "train_annotation.csv"), index=False)

#Annotation path
annotation_path = os.path.join(os.path.dirname(train_img),"train_annotation.csv")
annotation_path

# Training & Evaluating Using GPU
#initialize the model and change the corresponding config file
m = main.deepforest()
m.config['gpus'] = '-1' #move to GPU and use all the GPU resources
m.config["train"]["csv_file"] = annotation_path
m.config["train"]["root_dir"] = os.path.dirname(annotation_path)
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2
# m.config["train"]["fast_dev_run"] = True #for debugging
# m.config["validation"]["csv_file"] = validation_file
# m.config["validation"]["root_dir"] = os.path.dirname(validation_file)
# create a pytorch lighting trainer used to training
m.create_trainer()
#load the lastest release model
m.use_release()

start_time = time.time()
m.trainer.fit(m)
print(f"--- Training on GPU: {(time.time() - start_time):.2f} seconds [---")`]

Here is the image file: https://drive.google.com/file/d/11AndYOsK4lSlWB3CM3x5cmuxs5YnKCdJ/view?usp=sharing
Here is the hand annotated shapefile: https://drive.google.com/file/d/14rbB0muQ3FPG7aGITAZFn9qMuVLiIxzc/view?usp=sharing

Thanks!

**Comment by colbyrand** [comment] 2024-07-24 20:26
Here is the code I used:

#install packages
! pip install --upgrade deepforest
! pip install git+https://github.com/weecology/DeepForest.git

#load the modules
import os
import time
import numpy as np
import pandas as pd
from deepforest import main
from deepforest import get_data
from deepforest import utilities
from deepforest import preprocess
import geopandas as gpd
import matplotlib.pyplot as plt

#load model
model = main.deepforest()
model.use_release()

#accessing data from drive
from google.colab import drive
drive.mount('/content/drive')

#accessing the datasets
trainshp = '/content/drive/MyDrive/ACFL_Colab/Data/Crown_delin/Training/ACFL_Whistle_Lake_Training.shp'
train_img = '/content/drive/MyDrive/ACFL_Colab/Data/Imagery/ACFL_Whistle_Lake_Training_Area_Pictometry_2023_3in.tif'

#reading the raster
import rasterio as ras
train_img_file = ras.open(train_img)
transform = train_img_file.transform
crs = train_img_file.crs
crs

#predict the image (no training data)
boxes = model.predict_tile(train_img, return_plot = False, patch_size=700,
                           patch_overlap=0.25, iou_threshold= .4)
boxes.head()

gdf = utilities.annotations_to_shapefile(boxes, transform=transform, crs=crs)
gdf.to_file("/content/drive/MyDrive/ACFL_Colab/Data/Crown_delin/ACFL_Whistle_Lake_Training_Area_Crowns")

#predict the image (with training data)
#Visualizing the shapefile
trainshp_file =gpd.read_file(trainshp)
trainshp_file.plot()

#converting the training shapefile to annotations
df_train = utilities.shapefile_to_annotations(shapefile= (trainshp),
                                        rgb= (train_img) )
df_train.head()

#load the image file corresponding to the annotaion file
training_set_path = os.path.dirname(train_img)

#write converted dataframe to file. Saved alongside the images
df_train.to_csv(os.path.join(training_set_path, "train_annotation.csv"), index=False)

#annotation path
annotation_path = os.path.join(os.path.dirname(train_img),"train_annotation.csv")
annotation_path

#training & Evaluating Using GPU
#initialize the model and change the corresponding config file
m = main.deepforest()
m.config['gpus'] = '-1' #move to GPU and use all the GPU resources
m.config["train"]["csv_file"] = annotation_path
m.config["train"]["root_dir"] = os.path.dirname(annotation_path)
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2
#m.config["train"]["fast_dev_run"] = True #for debugging
#m.config["validation"]["csv_file"] = validation_file
#m.config["validation"]["root_dir"] = os.path.dirname(validation_file)
#create a pytorch lighting trainer used to training
m.create_trainer()
#load the lastest release model
m.use_release()

start_time = time.time()
m.trainer.fit(m)
print(f"--- Training on GPU: {(time.time() - start_time):.2f} seconds ---")

Here is the image: https://drive.google.com/file/d/11AndYOsK4lSlWB3CM3x5cmuxs5YnKCdJ/view?usp=sharing
Here is the hand annotated shapefile: https://drive.google.com/file/d/14rbB0muQ3FPG7aGITAZFn9qMuVLiIxzc/view?usp=sharing

Thanks!

**Comment by bw4sz** [comment] 2024-07-26 15:57
I started to debug this but you only included the .shp in the shapefile, it needs to be all fines. Better yet, can you just drop the .csv that you created. But really, something is very strange about your file. Have you looked at it? In preview on Mac it looks distorted and unrecognizable. I will give this a couple more minutes, but I think you just have a corrupted file. 

<img width="1321" alt="Screenshot 2024-07-26 at 8 56 16 AM" src="https://github.com/user-attachments/assets/e619d327-1bb6-4983-81aa-5ea8a4670b22">

**Comment by bw4sz** [comment] 2024-07-26 15:59
In QGIS it looks fine. 
<img width="1516" alt="Screenshot 2024-07-26 at 8 59 02 AM" src="https://github.com/user-attachments/assets/4b3ea2ad-2b8c-4187-8b00-3731de616a10">
i've not seen this before, let's continue.

**Comment by colbyrand** [comment] 2024-07-26 18:53
[ACFL_Whistle_Lake_Training.zip](https://github.com/user-attachments/files/16395727/ACFL_Whistle_Lake_Training.zip)
[train_annotation.csv](https://github.com/user-attachments/files/16395728/train_annotation.csv)

Thanks so much for taking a look! Here is the full shapefile and the csv file.

**Comment by colbyrand** [comment] 2024-07-30 21:53
Just wanted to check in to see if you were able to get that shapefile to load correctly. Let me know if anything else looks off! Thanks!

**Comment by colbyrand** [comment] 2024-07-31 19:00
Thanks so much for taking a look! I'm working with Robbie Andrus at Washington State University to conduct a forest canopy assessment survey in Anacortes, WA. The overarching goal of this project is to build a map of individual trees and tree species within the community forest lands, which will serve as a baseline for documenting future species-level changes in forest conditions over time. This will help us to map the spatial extent of recent tree mortality and place recent mortality in context of longer-term changes in forest canopy conditions. We are working with a 3" spatial resolution aerial orthomosaic of the forest, created in 2023.

Our specific goals are to (1) map individual tree crowns using the DeepForest package, and (2) validate those crowns with field surveys this summer where we are using the ArcGIS Field Maps app to record the tree species of crowns along trails in the forest. Thus, it would be helpful to have more accurate tree crowns by training the model using hand annotated crowns instead of using just the pre-trained model.

Eventually, we hope to use the tree species data we collected and the identified tree crowns to train a machine learning model to identify tree species across the entire forest.

**Comment by bw4sz** [comment] 2024-08-01 21:29
I can confirm the error with this more slim set of code.

```
import os
import pandas as pd
from deepforest import main

df_train = pd.read_csv("/Users/benweinstein/Downloads/ACFL_Whistle_Lake_Training_Area_Pictometry_2023_3in.csv")
train_img = "/Users/benweinstein/Downloads/ACFL_Whistle_Lake_Training_Area_Pictometry_2023_3in.tif"
#load the image file corresponding to the annotaion file
training_set_path = os.path.dirname(train_img)

#write converted dataframe to file. Saved alongside the images
df_train.to_csv(os.path.join(training_set_path, "train_annotation.csv"), index=False)

#annotation path
annotation_path = os.path.join(os.path.dirname(train_img),"train_annotation.csv")
annotation_path

#training & Evaluating Using GPU
#initialize the model and change the corresponding config file
m = main.deepforest()
m.config["train"]["csv_file"] = annotation_path
m.config["train"]["root_dir"] = os.path.dirname(annotation_path)
m.config["train"]["fast_dev_run"] = False 
m.create_trainer()

m.trainer.fit(m)
```

I am 99% this is isolated to this strange image that appears corrupted in Mac Preview, but looks fine on QGIS. We should be able to find a workaround or atleast raise an informative error. Where did you get this data, what preprocessing did you do?

**Comment by bw4sz** [comment] 2024-08-01 22:05
The image can be opened by rasterio, but it looks corrupted, so QGIS is a red herring, python don't see it correctly, you won't be able to train on it. PIL throws an error, which I actually appreciate. 

```
from PIL import Image
import PIL
import rasterio as rio
import matplotlib.pyplot as plt
import numpy as np

# Open the image using rasterio
image_path = "/Users/benweinstein/Downloads/ACFL_Whistle_Lake_Training_Area_Pictometry_2023_3in.tif"
try:
    dataset = rio.open(image_path)
    print("Rasterio: Image opened successfully")
    # Plot the image using matplotlib
    img = dataset.read()
    img = np.moveaxis(img, 0, -1)
    plt.imshow(img)
    plt.axis('off')
    plt.show()
except rio.errors.RasterioIOError as e:
    print(f"Rasterio: Failed to open image: {e}")

# Open the image using PIL
try:
    img = Image.open(image_path)
    print("PIL: Image opened successfully")
except (FileNotFoundError, PIL.UnidentifiedImageError) as e:
    print(f"PIL: Failed to open image: {e}")
```

<img width="653" alt="image" src="https://github.com/user-attachments/assets/98ed85e9-658c-487c-b3ac-d36e8047ab8d">

something is wrong with the dtypes. The image contains negative values.

```
>>> img.min()
-1.0
>>> img.max()
255.0
```
If you force the image to have integer dtype, not float, it visualizes correctly.

```
from PIL import Image
import PIL
import rasterio as rio
import matplotlib.pyplot as plt
import numpy as np

# Open the image using rasterio
image_path = "/Users/benweinstein/Downloads/ACFL_Whistle_Lake_Training_Area_Pictometry_2023_3in.tif"
try:
    dataset = rio.open(image_path)
    print("Rasterio: Image opened successfully")
    # Plot the image using matplotlib
    img = dataset.read()
    img = np.moveaxis(img, 0, -1)
    # Remove negative values and force them to 0
    #as integer
    img = np.array(img, dtype='uint')
    plt.imshow(img)
    plt.axis('off')
    plt.show()
except rio.errors.RasterioIOError as e:
    print(f"Rasterio: Failed to open image: {e}")

# Open the image using PIL
try:
    img = Image.open(image_path)
    print("PIL: Image opened successfully")
except (FileNotFoundError, PIL.UnidentifiedImageError) as e:
    print(f"PIL: Failed to open image: {e}")
```
<img width="653" alt="image" src="https://github.com/user-attachments/assets/8ae77fd4-4aa7-4359-9802-8e3b1f750100">

You probably need to drop the -1 in there you can see matplotlib compain about it as it plots. Set anything that is -1 to 0?

```
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
```

So however you access the image, the dtype is incorrect. I can confirm that this the error. This is how you fix it.

```
from PIL import Image
import PIL
import rasterio as rio
import matplotlib.pyplot as plt
import numpy as np

# Open the image using rasterio
image_path = "/Users/benweinstein/Downloads/ACFL_Whistle_Lake_Training_Area_Pictometry_2023_3in.tif"
try:
    dataset = rio.open(image_path)
    print("Rasterio: Image opened successfully")
    # Plot the image using matplotlib
    img = dataset.read()
    
    # Remove negative values and force them to 0
    #as integer
    img = np.array(img, dtype='uint')
    img[img < 0] = 0
    new_profile= dataset.profile
    new_profile.update(dtype='uint8')

    # change no data value
    new_profile.update(nodata=0)

    # save the image using rasterio with correct dtype
    with rio.open("output.tif", 'w', **new_profile) as dst:
        dst.write(img)

    # Move the channel axis to the last dimension for plotting
    img = np.moveaxis(img, 0, -1)
    plt.imshow(img)
    plt.axis('off')
    plt.show()
except rio.errors.RasterioIOError as e:
    print(f"Rasterio: Failed to open image: {e}")

# Open the image using PIL
try:
    img = Image.open(image_path)
    print("PIL: Image opened successfully")
except (FileNotFoundError, PIL.UnidentifiedImageError) as e:
    print(f"PIL: Failed to open image: {e}")

# Check output.tif is valid for PIL
try:
    img = Image.open("output.tif")
    print("PIL: Image opened successfully")
except (FileNotFoundError, PIL.UnidentifiedImageError) as e:
    print(f"PIL: Failed to open image: {e}")
```

The bigger question for us is how to anticipate these corrupt data. @ethanwhite or @henrykironde.

**Comment by bw4sz** [comment] 2024-08-01 22:10
I think the crux here is that the dtype is float, but the max value is 255.0, that is mixing two things. As matplotlib said, image convention is that float goes between 0-1, and int between 0-255. 

```
dataset.profile
{'driver': 'GTiff', 'dtype': 'float32', 'nodata': -1.0, 'width': 2995, 'height': 2401, 'count': 3, 'crs': CRS.from_epsg(26910), 'transform': Affine(0.07620015240030267, 0.0, 528272.4171640809,
       0.0, -0.07620015240017199, 5369795.934053496), 'blockxsize': 128, 'blockysize': 128, 'tiled': True, 'interleave': 'pixel'}
img = dataset.read()
img.max()
255.0
```

We could write a check to look for images that mix these?

**Comment by colbyrand** [comment] 2024-08-07 00:00
Thanks so much for all the code! I was able to use that to modify the image in a way that allowed it to be read by PIL, and I was able to successfully run m.trainer.fit(m). Now that I have a predictions result, how do I save that as a shapefile?

**Comment by bw4sz** [comment] 2024-08-07 14:41
It depends on what you mean, in terms of trying to save predictions as projected or unprojected data. Example: 
https://deepforest.readthedocs.io/en/latest/examples/Australia.html#Make-geospatial-predictions-on-the-full-tile
I'm going to close this issue, since the error has been resolved. Feel free to move to discussions for more help.

**Closed** 2024-08-07 14:43 UTC

**Comment by aeiche01** [comment] 2024-08-07 16:42
Just wanted to add to this: the inability to read the tiff file came up immediately after I attempted to aggregate the training tiffs to a coarser resolution. Running this code fixed the issue, but wanted to put this comment here in case someone else ran into the issue and is looking for aggregation as a keyword in the issues

**Comment by colbyrand** [comment] 2024-08-21 21:44
I just wanted to ask one more question if I could. I was able to run the code you posted to force the dtype to integer, but when I try to run this code on a much larger image, Google Collab crashes because it runs out of memory. What would be the best way to change the dtype on a large image without running out of RAM?

**Comment by bw4sz** [comment] 2024-08-21 22:41
Can't help you there, I'm not familiar with the in and out of colab. I doubt it, but maybe some kind of GDAL command line. Better to just work locally on a bigger machine, colab has gotten unstable and cheap, i've heard.

**Comment by ethanwhite** [comment] 2024-08-22 11:04
@colbyrand something like this may help (I used it to fix a similar issue in https://github.com/weecology/deepforestr/issues/13)

```sh
gdal_translate -ot Byte sample2.tif sample2_byte.tif
```
