### ISSUE TITLE
Multi Class Training not working.

### ISSUE THREAD

**Issue by Smart133594** [weecology/DeepForest#231] opened 2021-07-29 19:02 UTC
RuntimeError: Error(s) in loading state_dict for RetinaNet:
        size mismatch for head.classification_head.cls_logits.weight: copying a param with shape torch.Size([9, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([18, 256, 3, 3]).
        size mismatch for head.classification_head.cls_logits.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([18]).

When m.use_release()

If I use label_dict = {Tree:0}, this no happened.
But If I use label_dict={"Dead":0,"Alive":1}
This issue happened.

**Comment by Bognar791** [comment] 2021-08-02 00:23
Solved

**Comment by Mashood3624** [comment] 2021-08-12 08:01
How did you solve this issue ?
Kindly explain

**Comment by victoic** [comment] 2022-04-12 18:24
I would love to know as well.

**Comment by bzsklvnt** [comment] 2022-07-12 13:34
@Smart133594 what was your solution?

**Comment by Smart133594** [comment] 2022-07-12 14:59
That was my code issue, all is fine.

**Comment by Smart133594** [comment] 2022-07-12 15:37
I added some codes and that working now fully for the training.. 
All of trees detecting with tree names.
What is your email?

**Comment by bzsklvnt** [comment] 2022-07-12 15:43
Hi
Do you receive this email?

**Comment by Smart133594** [comment] 2022-07-12 15:44
No

**Comment by bzsklvnt** [comment] 2022-07-13 13:12
Please contact me at ***@***.*** !

Smart Dev ***@***.***> ezt írta (időpont: 2022. júl. 12., K,
17:44):

> No
>
> On Tue, Jul 12, 2022 at 11:43 AM Bozsoki Levente ***@***.***>
> wrote:
>
> > Hi
> > Do you receive this email?
> >
> >
> >

**Comment by EDGAR-BARAHONA** [comment] 2022-08-22 22:26
Buen dia, ala fecha de hoy sigo presentando el mismo problema mencionado.

the model strcuture is the next.

![image](https://user-images.githubusercontent.com/65068285/186029470-ec96cb4c-3c6a-4af6-907a-849d47579002.png)

the result of the model is the next.

![image](https://user-images.githubusercontent.com/65068285/186029611-1aa2a0c8-f38a-41a8-a8ba-1ba9c09d52fb.png)

**Comment by j-la-haye** [comment] 2022-11-04 09:47
@bzsklvnt @ethanwhite 

I am trying to test the multi class training and so far get no predictions using the provided testfile_multi.csv data.
If I place "fast_dev_run" to False to train for more than one epoch, I get the following error:

"Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor"

Any insight as to how you solved this or what I'm doing incorrectly would be appreciated. 

![Screenshot from 2022-11-04 10-43-15](https://user-images.githubusercontent.com/26750133/199942442-1720c26a-41b7-4a64-bbe8-7c8da85afce2.png)

![Screenshot from 2022-11-04 10-41-42](https://user-images.githubusercontent.com/26750133/199942257-ee318fd5-e878-462a-b049-c7dd3c817466.png)

**Comment by j-la-haye** [comment] 2022-11-04 10:35
Solved this error. Need to push the training to the GPU for second iteration. 
m.config['gpus'] = '1'

I still get terrible results on the provided test data and no predictions unless I use m.config["score_thresh"] = 0.01. 
Should this be the case (I understand its a tiny training set), but not sure if this is the result I should expect?

Thanks for any tips!
![SOAP_061](https://user-images.githubusercontent.com/26750133/199952631-123ab5a0-f99c-41ea-882d-37f98f0f33ba.png)

**Comment by ethanwhite** [comment] 2023-04-22 14:28
@j-la-haye We haven't actively explored multi-class modeling with trees using DeepForest and definitely not with tiny training sets. In general that would be a difficult problem. My one suggestion is that it looks like you aren't using the existing backbone and regression head (the parts of the model that help construct the bounding boxes around trees) and I suspect that is why the crown detection results are so bad.

I'm closing this since we've let it sit for too long (sorry about that) and since we're not actively supporting multi-class work yet, but feel free to open a new issue if you have additional questions.

**Closed by ethanwhite** 2023-04-22 14:28 UTC
