### ISSUE TITLE
follow up to previous issue

### ISSUE THREAD

**Issue by kristiyan-hristov** [weecology/DeepForest#212] opened 2021-07-13 08:14 UTC
Because the previous issue was closed I don't know if you will see the comment there that's why I create anew one. Please excuse me if this is troubling you!

![image](https://user-images.githubusercontent.com/78650985/125413516-b0fce931-b202-47e8-9ff2-a1b6a01422fe.png)
![image](https://user-images.githubusercontent.com/78650985/125413287-718acc71-290d-4734-8863-3525b14656a2.png)
![image](https://user-images.githubusercontent.com/78650985/125413395-acc82d84-a2d4-49b1-a1b7-431fc0bbacc6.png)

This is how my code, data and result look like the image that I predict after training is the same one that I have annotated beforehand so I want to compare the baseline prediction to the prediction after training.
Can you give me some clue what might be wrong?

Thanks in advance!

_Originally posted by @kristiyan-hristov in https://github.com/weecology/DeepForest-pytorch/issues/81#issuecomment-878864485_

**Comment by ethanwhite** [comment] 2021-07-13 11:47
@kristiyan-hristov - the issue is now here: https://github.com/weecology/DeepForest/issues/212

**Comment by kristiyan-hristov** [comment] 2021-07-13 12:08
![image](https://user-images.githubusercontent.com/78650985/125448908-e93504b9-7179-4974-8ca3-f8ae60996d74.png)
this is how I installed the package in colab (I use colab for the GPU)

**Comment by kristiyan-hristov** [comment] 2021-07-13 12:10
I followed this demo from your website: https://colab.research.google.com/drive/1gKUiocwfCvcvVfiKzAaf6voiUVL2KK_r?usp=sharing

**Comment by bw4sz** [comment] 2021-07-13 16:10
instead of the screenshot, can you just copy the code here or link the co-lab?

**Comment by kristiyan-hristov** [comment] 2021-07-13 16:42
https://colab.research.google.com/drive/1cy3vg7R-ueWuPSAowSKROgkNXFTZKA1k#scrollTo=knjd7JIKQp6x
should i send you the picture and the annotations as well?

**Comment by kristiyan-hristov** [comment] 2021-07-13 16:45
![450_01_01](https://user-images.githubusercontent.com/78650985/125492476-892ffae1-78f9-42c3-9f2c-06a7becf7acc.png)
this is the image

**Comment by kristiyan-hristov** [comment] 2021-07-13 16:47
The annotation file does not want to attach for some reason that's why I will just copy paste the content - it's not a lot 

image_path,xmin,ymin,xmax,ymax,label
450_01_01.png,8,69,80,162,Tree
450_01_01.png,79,35,127,82,Tree
450_01_01.png,135,2,239,70,Tree
450_01_01.png,53,278,159,362,Tree
450_01_01.png,138,302,226,388,Tree
450_01_01.png,97,224,169,296,Tree
450_01_01.png,127,183,219,262,Tree
450_01_01.png,202,138,269,204,Tree
450_01_01.png,241,93,310,151,Tree
450_01_01.png,300,77,332,114,Tree
450_01_01.png,309,53,395,106,Tree
450_01_01.png,576,36,653,108,Tree
450_01_01.png,378,14,446,69,Tree
450_01_01.png,743,322,814,392,Tree
450_01_01.png,794,284,903,355,Tree
450_01_01.png,655,263,757,345,Tree
450_01_01.png,626,287,689,360,Tree
450_01_01.png,571,494,639,539,Tree
450_01_01.png,468,500,583,593,Tree
450_01_01.png,792,486,872,551,Tree
450_01_01.png,812,420,934,537,Tree
450_01_01.png,913,385,982,461,Tree
450_01_01.png,965,446,1030,514,Tree
450_01_01.png,927,120,1015,207,Tree
450_01_01.png,785,221,836,262,Tree
450_01_01.png,748,191,806,244,Tree
450_01_01.png,748,253,806,308,Tree
450_01_01.png,783,156,846,213,Tree
450_01_01.png,833,197,891,261,Tree
450_01_01.png,921,63,986,120,Tree
450_01_01.png,998,36,1114,166,Tree
450_01_01.png,512,682,621,789,Tree
450_01_01.png,706,760,845,833,Tree
450_01_01.png,785,664,890,774,Tree
450_01_01.png,872,647,996,774,Tree
450_01_01.png,1016,633,1093,701,Tree
450_01_01.png,978,631,1032,705,Tree
450_01_01.png,1007,526,1079,600,Tree
450_01_01.png,1068,6,1142,96,Tree
450_01_01.png,14,616,147,717,Tree
450_01_01.png,4,524,87,625,Tree

**Comment by bw4sz** [comment] 2021-07-13 16:53
Thanks, i'll continue to think about this, but on first look I cannot reproduce.


```
from deepforest import main
m = main.deepforest()
Reading config file: deepforest_config.yml
m.use_release()
Downloading model from DeepForest release 1.0.0, see https://github.com/weecology/DeepForest/releases/tag/1.0.0 for details
Loading pre-built model: https://github.com/weecology/DeepForest/releases/tag/1.0.0
img = m.predict_image(path = "/Users/benweinstein/Downloads/issue.png",return_plot=True)
from matplotlib import pyplot as plt
plt.imshow(img[:,:,::-1])
```
Can you paste the output of the above and we can see how it differs.

<img width="637" alt="Screen Shot 2021-07-13 at 9 51 18 AM" src="https://user-images.githubusercontent.com/1208492/125493492-baeea566-1de5-421d-9f47-fb103ca5c5f6.png">

FYI i'm always looking for more annotations in urban areas to reduce that building prediction, if you have annotations to contribute that would be great.

**Comment by kristiyan-hristov** [comment] 2021-07-13 18:04
![image](https://user-images.githubusercontent.com/78650985/125502664-ba09cf14-93a3-435a-a4ef-c4f6c87bfa7c.png)

this is what I get from the code 

and the version

![image](https://user-images.githubusercontent.com/78650985/125502798-f86f5448-8b85-4bf0-af5d-f90227db8725.png)

**Comment by bw4sz** [comment] 2021-07-19 17:23
Closing this in favor of #215, follow along there.

**Closed by bw4sz** 2021-07-19 17:23 UTC
