### ISSUE TITLE
Dependencies in `setup.py` have module conflicts.

### ISSUE THREAD

**Issue by unsatisfying** [weecology/DeepForest#464] opened 2023-07-27 05:08 UTC
**Describe the bug**
There are two dependencies mentioned in the `setup.py` file: `opencv-python` and `albumentations` and the 'albumentations' depends on `opencv-python-headless`. The official [spec](https://pypi.org/project/opencv-contrib-python/)  mentioned that the `opencv-python` package is for the desktop environment, while `opencv-python-headless` is for the server environment. The documentation also states that these two packages cannot be installed simultaneously (the exact wording is: “There are four different packages (see options 1, 2, 3, and 4 below) and you should SELECT ONLY ONE OF THEM.”). This is because they both use the same module name cv2.

During the installation process using pip, the package installed later will override the cv2 module from the previously installed package (specifically, the modules within the cv2 folders that exist in both packages). Furthermore, the dependency graph even includes different versions of these two packages. It is certain that the common files with the same path in these two packages contain different contents. Therefore, there may be functional implications when using them. However, without analyzing the specific code and function call hierarchy of this project, it can be stated that issues related to overwriting and module conflicts do exist. 

**To Reproduce**
`pip install deepforest`

**Screenshots**
![image](https://github.com/weecology/DeepForest/assets/19465692/7df37ba5-35d7-4ba5-964a-207cc5d2a299)

**Additional context**
Indeed, it is not an ideal behavior for modules to be overwritten, even if they are not actively used or if the overwritten module is the one being called. It introduces uncertainty and can cause issues in the long run, especially if there are changes or updates to the overwritten modules in future development. It is generally recommended to avoid such conflicts and ensure that only the necessary and compatible dependencies are declared in the requirements to maintain a stable and predictable environment for the project. 

We believe that although this project can only modify direct dependencies and indirect dependencies are a black box, it is possible to add additional explanations rather than directly declaring both conflicting packages in the requirements.txt file.

Adding extra explanations or documentation about the potential conflicts and the need to choose only one of the conflicting packages can help developers understand the issue and make informed decisions. Including clear instructions or warnings in the project’s documentation can guide users to choose the appropriate package based on their specific requirements.

**Comment by bw4sz** [comment] 2023-08-03 17:44
Thanks for this. We'll need to look into it. Did this cause a specific error? *My gut feeling is that we can just rid of albumentations*. It has caused problems and i'm not convinced we actually need it.  Let's just go back to torchvision transforms and users can always add on from there.

**Comment by ethanwhite** [comment] 2024-03-25 23:00
Is this issue reproducible? It seems unlikely this is a broad issue since we install regularly on all sorts of testing environments, so this must be an edge case of sometime. I lean towards closing unless someone can duplicate.

**Comment by unsatisfying** [comment] 2024-04-09 09:46
> Is this issue reproducible? It seems unlikely this is a broad issue since we install regularly on all sorts of testing environments, so this must be an edge case of sometime. I lean towards closing unless someone can duplicate.

The fact that both are installed at the same time is not necessarily a serious problem, as it may overwrite modules that are not used or imported by your project, but it still causes the integrity of the user's native package to be compromised. However, this is also an aspect to consider when problems arise in the future.

**Comment by ethanwhite** [comment] 2024-04-17 11:38
Thanks @unsatisfying - this is a good point and I should have read the initial issue a little more carefully. We'll see what we can do

**Comment by bw4sz** [comment] 2024-08-11 22:59
I think that would be a great idea!

**Closed** 2024-08-17 22:44 UTC
Labels: good first issue, dependencies
