### ISSUE TITLE
Why does it show "No validation file provided. Turning off validation loop" when setting up the training path?

### ISSUE THREAD

**Issue by TSAI-ChengEn** [weecology/DeepForest#655] opened 2024-04-08 19:06 UTC
Codes:
```
#initial the model and change the corresponding config file
m = main.deepforest()
m.config['gpus'] = '-1' #move to GPU and use all the GPU resources
m.config["train"]["csv_file"] = "/content/drive/MyDrive/training_image/train_annotations.csv"
m.config["train"]["root_dir"] =  "/content/drive/MyDrive/training_image"
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2
m.config["validation"]["csv_file"] = "/content/drive/MyDrive/training_image/valid_annotations.csv"
m.config["validation"]["root_dir"] = "/content/drive/MyDrive/training_image"
#create a pytorch lighting trainer used to training
m.create_trainer()
#load the lastest release model
m.use_release()
```

I can confirm that all paths are correct, but I don't know why it always shows "No validation file provided. Turning off validation loop". I'm also unsure if this is the reason why the model trained afterward always fails to detect trees.

Codes are running using google colab.

Not sure what would be the problem here.

**Comment by bw4sz** [comment] 2024-04-15 16:38
Interesting. Let's make this a bit more reproducible, can you print the entire code, and show the config RIGHT before training. I'm wondering if by calling `use_release` after you set and create a trainer creates a strange pattern. That would be a bug, but i've never seen before. I'll need to see the full run or colab to make more insight. Let's get that sorted first, and then we can make sense of the model failing to detect trees. I'll need to know number of samples, what the images look like, and really the entire code to make sense of it.

**Comment by TSAI-ChengEn** [comment] 2024-04-18 21:38
Codes:`#load the modules
import os
import time
import numpy as np
from deepforest import main
from deepforest import get_data
from deepforest import utilities
from deepforest import preprocess
import pandas as pd
from sklearn.model_selection import train_test_split

# 讀取CSV檔案
df = pd.read_csv("/content/drive/MyDrive/Cluster3_annotations.csv")
# 調用 replace() 來替換 image_path 這一列中的路徑
df['image_path'] = df['image_path'].apply(lambda x: x.split('/')[-1])

# 檢查結果
print(df.head())

# 先將數據分割為訓練集和（驗證集+測試集），訓練集佔比70%（0.7）
train_df, other_df = train_test_split(df, test_size=0.3, random_state=42)

# 再從上一步產生的（驗證集+測試集）中分割驗證集和測試集，各自佔比50%，這樣在原始數據中的佔比就約為15%（0.3*0.5）
valid_df, test_df = train_test_split(other_df, test_size=0.5, random_state=42)

# 保存分割後的訓練集、驗證集和測試集

train_df.to_csv("/content/drive/MyDrive/training_image/train_annotations.csv", index=False)
valid_df.to_csv("/content/drive/MyDrive/training_image/valid_annotations.csv", index=False)
test_df.to_csv("/content/drive/MyDrive/training_image/test_annotations.csv", index=False)
annotations_file = "/content/drive/MyDrive/training_image/train_annotations.csv"
validation_file = "/content/drive/MyDrive/training_image/valid_annotations.csv"

#initial the model and change the corresponding config file
m = main.deepforest()
m.config['gpus'] = '-1' #move to GPU and use all the GPU resources
m.config["train"]["csv_file"] = annotations_file
m.config["train"]["root_dir"] = os.path.dirname(annotations_file)
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2
m.config["validation"]["csv_file"] = validation_file
m.config["validation"]["root_dir"] = os.path.dirname(validation_file)
#create a pytorch lighting trainer used to training
m.create_trainer()
#load the lastest release model
m.use_release()
start_time = time.time()
m.trainer.fit(m)
print(f"--- Training on GPU: {(time.time() - start_time):.2f} seconds ---")`
This is my entire code.
There are over 1000 samples.
![training_code1](https://github.com/weecology/DeepForest/assets/148372561/8bdc1eb1-3fd5-48d9-b163-4d4bf60735e2)
This is what my annotation looks like.
![trainig_image](https://github.com/weecology/DeepForest/assets/148372561/13b46e1e-09c9-45d1-9c08-191ad5c135d3)
This is what my images looks like.
![training_annotaion](https://github.com/weecology/DeepForest/assets/148372561/d9b6db4b-6e6f-49aa-a598-641db07dfdb4)
This is how it looks like with annotation boxes added to the image.

**Comment by ethanwhite** [comment] 2024-05-07 01:36
Looks like this is the same issue as #663. Sorry for losing track of this issues @TSAI-ChengEn.

**Comment by ethanwhite** [comment] 2024-05-07 02:07
@bw4sz - I suspect the reason we aren't typically seeing this is because we always have a validation file defined in `deepforest_config.yml`. Closing in favor of #664

**Closed by ethanwhite** 2024-05-07 02:07 UTC
